defaults: &defaults
  docker:
    - image: circleci/node:jessie-browsers

version: 2.1
jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Dependency install
          command: NODE_ENV=development npm ci
      - persist_to_workspace:
          root: ./
          paths:
            - node_modules

  audit:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Dependency audit
          command: npm audit
  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Code linting
          command: npm run lint
  coverage:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Code coverage
          command: npm run test:coverage

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Build from source
          command: npm run build
  publish:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Build from source
          command: npm run build
      - run:
          name: NPM deployment
          command: npx semantic-release

#      - persist_to_workspace:
#          root: ./
#          paths:
#            - node_modules
#            - lib
#      - run:
#          name: Commit
#          command: |
#            git config credential.helper 'cache --timeout=120'
#            git config user.email "daniel@ivin.nl"
#            git config user.name "Autobot"
#            git config --global push.default matching
#            git add .
#            git commit -m "ci: lib"
#            git checkout master
#            git merge -m "ci: merge" development
#            git push -q https://${gituser}:${gittoken}@github.com/djroberts/use-client master
workflows:
  version: 2
  build_and_test:
    jobs:
#      - dependencies:
#            filters:
#              tags:
#                only: /.*/
#      - audit:
#          filters:
#            tags:
#              only: /.*/
#      - lint:
#          filters:
#            tags:
#              only: /.*/
#      - coverage:
#          filters:
#            tags:
#              only: /.*/
#      - build:
#          context: usequery
#          requires:
#            - audit
#            - lint
#            - coverage
      - publish:
          context: usequery
          filters:
            branches:
              only:
                - master
