defaults: &defaults
  docker:
    - image: circleci/node:12.1.0

version: 2.1
jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Dependency install
          command: NODE_ENV=development npm ci
      - persist_to_workspace:
          root: ./
          paths:
            - node_modules

  audit:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Dependency audit
          command: npm audit
  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Code linting
          command: npm run lint
  coverage:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Code coverage
          command: npm run test:coverage

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Build from source
          command: npm run build
  publish:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Build from source
          command: npm run build
      - run:
          name: NPM deployment
          command: npx semantic-release
workflows:
  version: 2
  build_and_test:
    jobs:
#      - dependencies:
#            filters:
#              tags:
#                only: /.*/
#      - audit:
#          filters:
#            tags:
#              only: /.*/
      - lint:
          filters:
            tags:
              only: /.*/
      - coverage:
          filters:
            tags:
              only: /.*/
#      - build:
#          context: usequery
#          requires:
#            - audit
#            - lint
#            - coverage
      - publish:
          context: usecachedformikfield
          requires:
            - lint
            - coverage
          filters:
            branches:
              only:
                - master
